airtap/airtap

- README.md
- bin/airtap
- doc/airtap.yml.md
- doc/cloud-testing.md
- example/.airtap.yml
This is a small step towards #9. Closes #32.
> Set default UI to tape and remove option from docs

- frameworks/zuul.js
- package.json
Closes https://github.com/airtap/airtap/issues/50
> remove JSON2

- bin/airtap.js
- lib/zuul.js
- test/integration/jamine-phantom.js
- test/integration/mocha-qunit-phantom.js
- test/integration/mochabdd-phantom.js
- test/integration/tape-phantom.js
Closes https://github.com/airtap/airtap/issues/46
> fix: zuul.run(cb) calls back with (err, passed)

- CONTRIBUTING.md
- README.md
Closes https://github.com/airtap/airtap/issues/12
> Add open open source contribution guide

- README.md
> Add a "Who Uses Airtap?" section to readme

- bin/airtap.js
- lib/Electron.js
- lib/PhantomBrowser.js
- package.json
See [chalk#origin-story](https://github.com/chalk/chalk\#origin-story) for explanation.
<hr />
Closes #83.
> Replace `colors` with `chalk`

- bin/airtap.js
- lib/control-app.js
> remove .ui/--ui option

- package.json
> remove mocha

- doc/airtap.yml.md
- doc/travis-matrix.md
> remove references to ember in doc/ + update travis example using tape

- frameworks/render-stacktrace.js
- frameworks/tape.js
- frameworks/zuul.js
- lib/airtap.js
- lib/builder-browserify.js
- lib/control-app.js
- lib/electron-browser.js
- lib/electron-inject.js
- lib/electron-run.js
- lib/flatten-browserlist.js
- lib/get-saucelabs-browsers.js
- lib/phantom-browser.js
- lib/phantom-run.js
- lib/sauce-browser.js
- lib/setup.js
- lib/user-server.js
- package.json
- test/auth.js
- test/fixtures/builder-browserify/bar-to-baz-plugin.js
- test/fixtures/builder-browserify/baz-to-qux-transform.js
- test/fixtures/builder-browserify/entry.js
- test/fixtures/builder-browserify/foo-to-bar-transform.js
- test/fixtures/tape/test.js
- test/integration/tape-phantom.js
- test/integration/tape-sauce.js
- test/unit/browserify-builder.js
- test/unit/capabilities.js
I've tried to make each commit be about the same type of error.
Closes https://github.com/airtap/airtap/issues/87 and https://github.com/airtap/airtap/issues/42
Will squash.
> Finalize standard

- .travis.yml
- lib/electron-inject.js
- lib/electron-run.js
- test/index.js
- test/integration/tape-electron.js
Opening this PR for feedback. The integration test for electron runs fine for me locally. Wondering why it fails on Travis. Do I need something extra setup on Travis to make it work?
Possibly related: https://electronjs.org/docs/tutorial/testing-on-headless-ci
> add integration test for electron

- lib/electron-browser.js
- package.json
Closes https://github.com/airtap/airtap/issues/109
> use electron instead of deprecated electron-prebuilt

- bin/airtap.js
> Throw error instead of error message string

- lib/sauce-browser.js
> Debug error if setting Sauce Labs job status failed

- lib/setup.js
Closes https://github.com/airtap/airtap/issues/96
> setup: opt -> opts and config -> opts, remove controlPort variable

- lib/sauce-browser.js
Closes https://github.com/airtap/airtap/issues/104
> replace IIFE with normal function declaration and function call

- lib/electron-inject.js
- lib/electron-run.js
> remove support for old electron api + refactor

- package.json
```diff
- "qunit",
- "mocha",
+ "tap",
+ "tape"
```
Nit: Also arranged them alphabetically 😋
<hr />
Closes #120
> Update keywords in `package.json`

- .travis.yml
- package.json
Closes https://github.com/airtap/airtap/issues/102
> remove support for node 4

- package.json
Quick note:
<hr />
Closes #122
> Update `dependency-check` to latest

- bin/airtap.js
- lib/messages.js
- test/index.js
- test/unit/airtap.js
Closes https://github.com/airtap/airtap/issues/66
Will squash.
> Exit cleanly if Travis has no secure environment variables

- package.json
Closes https://github.com/airtap/airtap/issues/113
> dependency-check: entries for integration and unit tests not needed

- CHANGELOG.md
> changelog: prepare changelog for 0.0.4

- lib/airtap.js
- lib/electron-browser.js
- lib/phantom-browser.js
Small stuff, working towards an `AbstractBrowser`. See https://github.com/airtap/airtap/issues/95#issuecomment-368245561.
> Rename status to stats for consistency

- lib/control-app.js
- package.json
See https://github.com/airtap/airtap/issues/93#issuecomment-368244277.
> Terminate connections with server-destroy

- lib/electron-browser.js
- package.json
> Add test-local-electron script

- lib/sauce-browser.js
> Rename SauceBrowser#browser to webdriver

- lib/abstract-browser.js
- lib/electron-browser.js
- lib/phantom-browser.js
- lib/sauce-browser.js
> Introduce AbstractBrowser

- test/unit/airtap.js
> Fix CLI test on windows

- test/abstract-browser/abstract-browser.js
- test/abstract-browser/electron-browser.js
- test/abstract-browser/phantom-browser.js
- test/abstract-browser/sauce-browser.js
- test/index.js
Mostly a skeleton with various skipped tests, to have something to aim for.
> Test abstract browser and implementations

- lib/abstract-browser.js
- lib/electron-browser.js
- lib/phantom-browser.js
- lib/sauce-browser.js
Move `.stats` to `AbstractBrowser`.
Closes https://github.com/airtap/airtap/issues/95
> Abstract start

- lib/sauce-browser.js
> Remove dead tags option

- bin/airtap.js
- lib/electron-browser.js
- lib/phantom-browser.js
- test/unit/airtap.js
> Prefer debug

- lib/builder-browserify.js
- lib/control-app.js
Closes #159 and helps with #152.
> Don't watch node_modules

- CHANGELOG.md
> Prepare 0.0.7

- bin/airtap.js
- lib/builder-browserify.js
- lib/control-app.js
Closes https://github.com/airtap/airtap/issues/158
> Do not watchify if process.env.CI is defined

- client/reporter.js
- lib/control-app.js
- package.json
Closes https://github.com/airtap/airtap/issues/156
> Remove istanbul-middleware and disable coverage temporarily

- bin/airtap.js
- client/reporter.js
- lib/airtap.js
- test/integration/tape-electron.js
- test/integration/tape-sauce.js
- test/integration/verify-common.js
- test/unit/airtap.js
Closes https://github.com/airtap/airtap/issues/179
> Zuul -> Airtap and ZuulReporter -> Reporter

- CHANGELOG.md
- lib/control-app.js
Closes #200. Ready for release.
> Increase maximum body size for posting code coverage

- client/index.css
- client/reporter.js
Closes https://github.com/airtap/airtap/issues/202
> Remove code coverage tab

- README.md
- UPGRADING.md
- bin/airtap.js
- doc/debugging.md
- doc/travis-ci.md
- lib/airtap.js
- lib/sauce-browser.js
- lib/setup.js
- test/integration/tape-electron.js
- test/integration/tape-mock-sauce.js
- test/integration/tape-sauce.js
- test/unit/airtap.js
> Refactor options

- package.json
> fix(package): update wd to version 1.11.1

- client/reporter.js
- package.json
Closes #228. I also took the opportunity to improve error feedback.
> Replace superagent with xhr

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- UPGRADING.md
- package.json
> Prepare 1.0.0

- package.json
> greenkeeper: ignore tap-parser

- package.json
> Upgrade electron devDependency from ^4.1.2 to ^5.0.6

- lib/bundler.js
- package.json
In order to include devongovett/browserify-istanbul#45.
Closes #296.
> Replace browserify-istanbul with @airtap fork

- README.md
Ref https://github.com/badges/shields/issues/8671.
> doc: fix warning in CI status badge
